### PR TITLE
patched

### PR DESCRIPTION
**Pull request by Krowe-moh**

### CODE REVIEW

**Comment by Playeereq** [comment]
?

**Comment by Krowe-moh** [comment]
The request sends a error

**Comment by PRO100KatYT** [comment]
The request doesn't send any errors for me. If you're using a new account, make sure to open fortnite on it at least once so it gains permission to interact with the API.

**Comment by Krowe-moh** [comment]
Yes i know but the request doesn't do anything anymore it only sends a 200 with queryprofile response

**Comment by PRO100KatYT** [comment]
I tested it on a new account and it completed the tutorial and gave me the music pack.

**Comment by Krowe-moh** [comment]
what???

**Comment by Krowe-moh** [comment]
never mind seems like they only patched other stuff

**Pull request closed without merging**
